(in-package :bknr.text)

(define-bknr-tag paste-form ()
  (html ((:form :method "POST")
	 (:table (:tr (:td "subject")
		      (:td (text-field "subject")))
		 (:tr (:td "message")
		      (:td (textarea-field "text")))
		 (:tr ((:td))
		      (:td (checkbox-field "lisp" "LISP code")))
		 (:tr ((:td :colspan 2)
		       (submit-button "create" "create")))))))

(define-bknr-tag paste-annotate-form ()
  (html ((:form :method "POST")
	 (:table (:tr (:td "message")
		      (:td (textarea-field "text")))
		 (:tr ((:td))
		      (:td (checkbox-field "lisp" "LISP code")))
		 (:tr ((:td :colspan 2)
		       (submit-button "annotate" "annotate")))))))

(defun show-paste (paste)
  (html ((:div :class "textbox_3")
	 (article-blog-headline paste)
	 (if (member :lisp (keywords-article-keywords paste))
	     (htmlize-string (article-text paste) *html-stream*)
	     (let ((msg (regex-replace-all "[\\r\\n]"
					   (html-quote (article-text paste))
					   "<br />")))
	       (html (:princ msg)))))))
  
(define-bknr-tag paste (paste)
  (show-paste paste)
  (html (:h2 "annotations:"))
  (dolist (annotation (reverse (annotated-article-annotations paste)))
    (show-paste annotation)))
